enum class HeroBoard(
    val title: String,
    val complexity: Int,
    val attack: Pair<Int, Int>,
    val defense: Pair<Int, Int>,
    val initiative: Pair<Int, Int>,
    val movement: Pair<Int, Int>,
    val tags: List<Tag>,
    val pack: HeroPack,
) {
    Arien("the Tidemaster", 1, 8 to 8, 5 to 6, 4 to 4, 5 to 6, listOf(Tag.Tactician, Tag.Disabler, Tag.Durable, Tag.Pusher), HeroPack.BASE),
    Brogan("the Destroyer", 1, 7 to 7, 8 to 8, 1 to 1, 2 to 4, listOf(Tag.Durable, Tag.Disabler, Tag.Pusher, Tag.Farming), HeroPack.BASE),
    Dodger("the Warlock", 1, 3 to 3, 2 to 5, 7 to 7, 5 to 5, listOf(Tag.Damager, Tag.Sniper, Tag.Pusher, Tag.Farming, Tag.Disabler), HeroPack.BASE),
    Sabina("the Commander", 1, 1 to 7, 3 to 3, 5 to 5, 5 to 6, listOf(Tag.Tactician, Tag.Pusher), HeroPack.BASE),
    Tigerclaw("the Cutpurse", 1, 4 to 8, 1 to 4, 8 to 8, 7 to 8, listOf(Tag.Melee, Tag.Disabler, Tag.Farming), HeroPack.BASE),
    Wasp("the Warmaiden", 1, 5 to 5, 4 to 5, 6 to 6, 5 to 5, listOf(Tag.Disabler, Tag.Tactician, Tag.Sniper), HeroPack.BASE),
    Xargatha("the Changed", 1, 5 to 8, 6 to 6, 3 to 3, 6 to 6, listOf(Tag.Tactician, Tag.Pusher, Tag.Disabler, Tag.Durable, Tag.Sniper), HeroPack.BASE),
    Bain("the Bounty Hunter", 2, 5 to 5, 4 to 6, 4 to 4, 5 to 6, listOf(Tag.Tactician, Tag.Sniper, Tag.Healer, Tag.Farming, Tag.Durable), HeroPack.DEFIANT),
    Garrus("the Gladiator", 2, 8 to 8, 7 to 7, 3 to 3, 5 to 6, listOf(Tag.Disabler, Tag.Durable, Tag.Tactician), HeroPack.DEFIANT),
    Min("the Dragonmonk", 2, 4 to 8, 3 to 8, 8 to 8, 6 to 6, listOf(Tag.Tokens, Tag.Disabler, Tag.Damager, Tag.Melee), HeroPack.RENOWNED),
    Misa("the Samurai", 2, 6 to 6, 5 to 5, 7 to 7, 1 to 8, listOf(Tag.Tactician, Tag.Durable, Tag.Damager), HeroPack.DEVOTED),
    Rowenna("the Vanguard", 2, 8 to 8, 7 to 7, 4 to 4, 3 to 5, listOf(Tag.Melee, Tag.Durable, Tag.Healer, Tag.Farming, Tag.Pusher, Tag.Tactician), HeroPack.ARCANE),
    Silverarrow("the Pathfinder", 2, 2 to 2, 1 to 1, 7 to 7, 6 to 7, listOf(Tag.Sniper, Tag.Damager, Tag.Disabler, Tag.Healer, Tag.Farming), HeroPack.DEVOTED),
    Ursafar("the Savage", 2, 6 to 6, 6 to 6, 5 to 5, 1 to 5, listOf(Tag.Durable, Tag.Pusher, Tag.Farming, Tag.Melee), HeroPack.DEVOTED),
    Whisper("the Outcast", 2, 7 to 7, 4 to 4, 7 to 7, 3 to 5, listOf(Tag.Damager, Tag.Durable, Tag.Tactician, Tag.Pusher), HeroPack.DEVOTED),
    Brynn("the Seeker", 3, 4 to 8, 4 to 4, 7 to 7, 5 to 6, listOf(Tag.Tactician, Tag.Damager, Tag.Durable), HeroPack.WAYWARD),
    Cutter("the Sky Pirate", 3, 4 to 8, 4 to 4, 6 to 6, 4 to 8, listOf(Tag.Tactician, Tag.Damager, Tag.Farming), HeroPack.DEFIANT),
    Hanu("the Trickster", 3, 4 to 4, 1 to 1, 8 to 8, 8 to 8, listOf(Tag.Tactician, Tag.Sniper, Tag.Pusher), HeroPack.RENOWNED),
    Mortimer("the Awakener", 3, 8 to 8, 7 to 7, 2 to 2, 4 to 4, listOf(Tag.Melee, Tag.Tokens, Tag.Farming, Tag.Durable, Tag.Pusher), HeroPack.WAYWARD),
    Mrak("the Rockshaper", 3, 8 to 8, 8 to 8, 1 to 1, 2 to 4, listOf(Tag.Melee, Tag.Tokens, Tag.Durable, Tag.Disabler, Tag.Tactician), HeroPack.ARCANE),
    Swift("the Sharpshooter", 3, 5 to 5, 2 to 2, 4 to 4, 3 to 7, listOf(Tag.Sniper, Tag.Farming, Tag.Tactician), HeroPack.RENOWNED),
    Tali("the Spiritcaller", 3, 4 to 6, 4 to 4, 5 to 8, 5 to 5, listOf(Tag.Damager, Tag.Pusher, Tag.Healer, Tag.Durable, Tag.Tokens), HeroPack.DEVOTED),
    Trinkets("the Scavenger", 3, 3 to 5, 2 to 4, 6 to 6, 7 to 8, listOf(Tag.Sniper, Tag.Damager, Tag.Pusher, Tag.Tokens), HeroPack.DEFIANT),
    Widget("and Pyro", 3, 5 to 5, 4 to 4, 4 to 4, 5 to 6, listOf(Tag.Tactician, Tag.Pusher, Tag.Damager), HeroPack.WAYWARD),
    Wuk("the Grove Keeper", 3, 5 to 5, 8 to 8, 1 to 1, 3 to 4, listOf(Tag.Tokens, Tag.Pusher, Tag.Durable, Tag.Sniper, Tag.Tactician, Tag.Healer), HeroPack.RENOWNED),
    Emmitt("the Traveller", 4, 5 to 8, 6 to 6, 1 to 1, 2 to 4, listOf(Tag.Melee, Tag.Tactician, Tag.Durable, Tag.Disabler, Tag.Tokens), HeroPack.WAYWARD),
    Gydion("the Archwizard", 4, 5 to 6, 3 to 5, 3 to 3, 1 to 4, listOf(Tag.Sniper, Tag.Tactician, Tag.Farming, Tag.Damager, Tag.Pusher, Tag.Tokens), HeroPack.ARCANE),
    Ignatia("the Mad", 4, 5 to 5, 6 to 6, 2 to 2, 4 to 5, listOf(Tag.Sniper, Tag.Damager, Tag.Tokens, Tag.Tactician, Tag.Pusher), HeroPack.RENOWNED),
    NebKher("the Harbinger", 4, 2 to 3, 5 to 6, 1 to 1, 2 to 5, listOf(Tag.Disabler, Tag.Tokens, Tag.Sniper), HeroPack.DEFIANT),
    Razzle("the Ringmaster", 4, 3 to 3, 1 to 4, 8 to 8, 5 to 6, listOf(Tag.Tactician, Tag.Melee), HeroPack.ARCANE),
    Snorri("the Runescribe", 4, 5 to 6, 5 to 6, 2 to 2, 4 to 5, listOf(Tag.Sniper, Tag.Farming, Tag.Durable, Tag.Damager, Tag.Pusher, Tag.Healer), HeroPack.ARCANE),
    Takahide("the Warlord", 4, 5 to 7, 4 to 7, 3 to 5, 1 to 4, listOf(Tag.Durable, Tag.Sniper, Tag.Tactician, Tag.Damager, Tag.Farming), HeroPack.WAYWARD),
}
